#! /bin/bash

redroot="/home/user/red/red"
redargs="-r"

cmd=$1

if [ "$cmd" = "--root" ]; then
	shift
	redroot=$1
	shift
	cmd=$1
fi

if [ "$cmd" = "--args" ]; then
	shift
	redargs=$1
	shift
	cmd=$1
fi

redfile="$cmd"
echo "Rebol[] do/args %${redroot}/red.r \"${redargs} %${redfile}\"" | rebol +q -s