#! /bin/bash

redroot="/home/user/red/red"
redargs="-r"
redmv="false"

cmd=$1

if [ "$cmd" = "--root" ]; then
	shift
	redroot=$1
	shift
	cmd=$1
fi

if [ "$cmd" = "--args" ]; then
	shift
	redargs=$1
	shift
	cmd=$1
fi

if [ "$cmd" = "--mv" ]; then
	redmv="true"
	shift
	cmd=$1
fi

redfile="$cmd"
echo "Rebol[] do/args %${redroot}/red.r \"${redargs} %${redfile}\"" | rebol +q -s
if [ "$redmv" = "true" ]; then 
	redbin="/home/user/work/.RedGTK"
	basename=$(basename ${redfile})
	mkdir -p $redbin
	mv "${basename%.*}" $redbin/
fi